-- Schema: gu
-- CacaoMARKETCM application database namespace.
-- This script is tracked for manual execution; it is not run automatically by Spring Boot.

BEGIN;

CREATE SCHEMA IF NOT EXISTS gu AUTHORIZATION sorelle;

-- Table: Type utilisateur
-- The lookup values determine whether an utilisateur is a client, vendeur, or administrateur.
CREATE TABLE IF NOT EXISTS gu.type_utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    tu_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_type_utilisateur_code UNIQUE (code),
    CONSTRAINT uq_type_utilisateur_name UNIQUE (tu_name)
);

INSERT INTO gu.type_utilisateur (code, tu_name)
VALUES
    ('CLIENT', 'Client'),
    ('VENDEUR', 'Vendeur'),
    ('ADMINISTRATEUR', 'Administrateur')
ON CONFLICT (code) DO UPDATE
SET tu_name = EXCLUDED.tu_name;

-- Table: Utilisateurs
CREATE TABLE IF NOT EXISTS gu.utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_utilisateur_id BIGINT NOT NULL REFERENCES gu.type_utilisateur(id),
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'ACTIF',
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_utilisateurs_email UNIQUE (email),
    CONSTRAINT uq_utilisateurs_login UNIQUE (login)
);

CREATE INDEX IF NOT EXISTS idx_utilisateurs_type_utilisateur
    ON gu.utilisateurs (type_utilisateur_id);

-- Registration and login compare identities without regard to case.
CREATE UNIQUE INDEX IF NOT EXISTS uq_utilisateurs_email_lower
    ON gu.utilisateurs (LOWER(email));

CREATE UNIQUE INDEX IF NOT EXISTS uq_utilisateurs_login_lower
    ON gu.utilisateurs (LOWER(login));

-- Buyer profiles are separated from the common account table. A CLIENT either represents a
-- private individual or an enterprise; prenom/nom on utilisateurs remain the person creating the
-- account (the legal representative/contact for an enterprise).
CREATE TABLE IF NOT EXISTS gu.client_particulier (
    utilisateur_id BIGINT PRIMARY KEY REFERENCES gu.utilisateurs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gu.client_entreprise (
    utilisateur_id BIGINT PRIMARY KEY REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    raison_sociale VARCHAR(150) NOT NULL,
    niu VARCHAR(50) NOT NULL,
    rccm VARCHAR(50) NOT NULL,
    CONSTRAINT chk_client_entreprise_raison_sociale_not_blank CHECK (BTRIM(raison_sociale) <> ''),
    CONSTRAINT chk_client_entreprise_niu_not_blank CHECK (BTRIM(niu) <> ''),
    CONSTRAINT chk_client_entreprise_rccm_not_blank CHECK (BTRIM(rccm) <> '')
);

-- NIU and RCCM are stored in a normalized upper-case form by the API. Case-insensitive indexes
-- keep direct database writes from creating a conflicting spelling of the same identifier.
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_entreprise_niu_upper
    ON gu.client_entreprise (UPPER(niu));

CREATE UNIQUE INDEX IF NOT EXISTS uq_client_entreprise_rccm_upper
    ON gu.client_entreprise (UPPER(rccm));

-- Stop rather than guessing if a previously partial/manual rollout has already created
-- contradictory profile data. The later backfill handles only unambiguous legacy CLIENT rows.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM gu.client_particulier AS cp
        INNER JOIN gu.client_entreprise AS ce ON ce.utilisateur_id = cp.utilisateur_id
    ) THEN
        RAISE EXCEPTION 'A CLIENT account cannot have both buyer profile types; resolve the conflicting rows before applying this migration.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM (
            SELECT utilisateur_id FROM gu.client_particulier
            UNION ALL
            SELECT utilisateur_id FROM gu.client_entreprise
        ) AS profile
        INNER JOIN gu.utilisateurs AS u ON u.id = profile.utilisateur_id
        INNER JOIN gu.type_utilisateur AS tu ON tu.id = u.type_utilisateur_id
        WHERE tu.code <> 'CLIENT'
    ) THEN
        RAISE EXCEPTION 'Only CLIENT accounts can have buyer profiles; resolve the invalid rows before applying this migration.';
    END IF;
END;
$$;

-- Both profile tables reference only CLIENT accounts and are mutually exclusive. Locking the
-- account row makes concurrent profile inserts deterministic rather than allowing two profile
-- types to be created simultaneously.
CREATE OR REPLACE FUNCTION gu.enforce_client_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    is_client BOOLEAN;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.utilisateur_id IS DISTINCT FROM OLD.utilisateur_id THEN
        RAISE EXCEPTION 'A client profile cannot be moved to another utilisateur.';
    END IF;

    PERFORM 1
    FROM gu.utilisateurs
    WHERE id = NEW.utilisateur_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'A client profile requires an existing utilisateur.';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM gu.utilisateurs AS u
        INNER JOIN gu.type_utilisateur AS tu ON tu.id = u.type_utilisateur_id
        WHERE u.id = NEW.utilisateur_id
          AND tu.code = 'CLIENT'
    )
    INTO is_client;

    IF NOT is_client THEN
        RAISE EXCEPTION 'Only CLIENT accounts can have a buyer profile.';
    END IF;

    IF TG_TABLE_NAME = 'client_particulier' THEN
        IF EXISTS (SELECT 1 FROM gu.client_entreprise WHERE utilisateur_id = NEW.utilisateur_id) THEN
            RAISE EXCEPTION 'A CLIENT account cannot have both buyer profile types.';
        END IF;
    ELSIF EXISTS (SELECT 1 FROM gu.client_particulier WHERE utilisateur_id = NEW.utilisateur_id) THEN
        RAISE EXCEPTION 'A CLIENT account cannot have both buyer profile types.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_client_particulier_enforce_profile ON gu.client_particulier;

CREATE TRIGGER trg_client_particulier_enforce_profile
BEFORE INSERT OR UPDATE ON gu.client_particulier
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_client_profile();

DROP TRIGGER IF EXISTS trg_client_entreprise_enforce_profile ON gu.client_entreprise;

CREATE TRIGGER trg_client_entreprise_enforce_profile
BEFORE INSERT OR UPDATE ON gu.client_entreprise
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_client_profile();

-- A profile cannot remain attached to a non-CLIENT account after a direct administrative role
-- change. Delete/reclassify the profile deliberately before changing the account's role.
CREATE OR REPLACE FUNCTION gu.prevent_client_profile_role_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.type_utilisateur_id IS DISTINCT FROM OLD.type_utilisateur_id
        AND (EXISTS (SELECT 1 FROM gu.client_particulier WHERE utilisateur_id = OLD.id)
            OR EXISTS (SELECT 1 FROM gu.client_entreprise WHERE utilisateur_id = OLD.id))
        AND NOT EXISTS (
            SELECT 1
            FROM gu.type_utilisateur
            WHERE id = NEW.type_utilisateur_id
              AND code = 'CLIENT'
        ) THEN
        RAISE EXCEPTION 'A buyer profile cannot be attached to a non-CLIENT account.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_utilisateurs_preserve_client_profile_role ON gu.utilisateurs;

CREATE TRIGGER trg_utilisateurs_preserve_client_profile_role
BEFORE UPDATE OF type_utilisateur_id ON gu.utilisateurs
FOR EACH ROW
EXECUTE FUNCTION gu.prevent_client_profile_role_change();

-- A deferred constraint closes the remaining gap: a CLIENT can be inserted together with its
-- profile in one transaction, but cannot commit with zero or two profiles. The deferred timing
-- also permits a deliberate particular-to-enterprise reclassification in a future controlled
-- workflow without exposing an intermediate invalid state.
CREATE OR REPLACE FUNCTION gu.enforce_exactly_one_client_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    profile_utilisateur_id BIGINT;
    is_client BOOLEAN;
    has_particulier_profile BOOLEAN;
    has_entreprise_profile BOOLEAN;
BEGIN
    IF TG_TABLE_NAME = 'utilisateurs' THEN
        profile_utilisateur_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.id
            ELSE NEW.id
        END;
    ELSE
        profile_utilisateur_id := CASE
            WHEN TG_OP = 'DELETE' THEN OLD.utilisateur_id
            ELSE NEW.utilisateur_id
        END;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM gu.utilisateurs AS u
        INNER JOIN gu.type_utilisateur AS tu ON tu.id = u.type_utilisateur_id
        WHERE u.id = profile_utilisateur_id
          AND tu.code = 'CLIENT'
    )
    INTO is_client;

    IF NOT is_client THEN
        RETURN NULL;
    END IF;

    SELECT EXISTS (SELECT 1 FROM gu.client_particulier WHERE utilisateur_id = profile_utilisateur_id)
    INTO has_particulier_profile;
    SELECT EXISTS (SELECT 1 FROM gu.client_entreprise WHERE utilisateur_id = profile_utilisateur_id)
    INTO has_entreprise_profile;

    IF has_particulier_profile = has_entreprise_profile THEN
        RAISE EXCEPTION 'A CLIENT account must have exactly one buyer profile.';
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_utilisateurs_require_client_profile ON gu.utilisateurs;

CREATE CONSTRAINT TRIGGER trg_utilisateurs_require_client_profile
AFTER INSERT OR UPDATE OR DELETE ON gu.utilisateurs
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_exactly_one_client_profile();

DROP TRIGGER IF EXISTS trg_client_particulier_require_exactly_one_profile ON gu.client_particulier;

CREATE CONSTRAINT TRIGGER trg_client_particulier_require_exactly_one_profile
AFTER INSERT OR UPDATE OR DELETE ON gu.client_particulier
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_exactly_one_client_profile();

DROP TRIGGER IF EXISTS trg_client_entreprise_require_exactly_one_profile ON gu.client_entreprise;

CREATE CONSTRAINT TRIGGER trg_client_entreprise_require_exactly_one_profile
AFTER INSERT OR UPDATE OR DELETE ON gu.client_entreprise
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_exactly_one_client_profile();

-- Existing CLIENT accounts predate the explicit buyer-profile model. Classify them safely as
-- private individuals until an administrator deliberately records an enterprise profile.
INSERT INTO gu.client_particulier (utilisateur_id)
SELECT u.id
FROM gu.utilisateurs AS u
INNER JOIN gu.type_utilisateur AS tu ON tu.id = u.type_utilisateur_id
WHERE tu.code = 'CLIENT'
  AND NOT EXISTS (
      SELECT 1
      FROM gu.client_entreprise AS ce
      WHERE ce.utilisateur_id = u.id
  )
ON CONFLICT (utilisateur_id) DO NOTHING;

-- Table: Connected browser sessions
-- One row is created after each successful login. The raw servlet/JSESSIONID value is never
-- stored; session_hash is a SHA-256 hash so several browser sessions can be managed safely.
CREATE TABLE IF NOT EXISTS gu.sessions_utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    session_hash CHAR(64) NOT NULL,
    browser_label VARCHAR(120) NOT NULL,
    remember_me BOOLEAN NOT NULL DEFAULT FALSE,
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    invalidated_at TIMESTAMPTZ,
    CONSTRAINT uq_sessions_utilisateur_session_hash UNIQUE (session_hash),
    CONSTRAINT chk_sessions_utilisateur_dates CHECK (
        last_seen_at >= date_creation
        AND expires_at >= last_seen_at
        AND (invalidated_at IS NULL OR invalidated_at >= date_creation)
    )
);

CREATE INDEX IF NOT EXISTS idx_sessions_utilisateur_utilisateur_active
    ON gu.sessions_utilisateur (utilisateur_id, last_seen_at DESC)
    WHERE invalidated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sessions_utilisateur_expiration_active
    ON gu.sessions_utilisateur (expires_at)
    WHERE invalidated_at IS NULL;

-- Table: Registration confirmations
-- A pending utilisateur receives one hashed, single-use email-confirmation token.
-- Raw tokens are deliberately never stored in PostgreSQL.
CREATE TABLE IF NOT EXISTS gu.registration_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_registration_confirmation_utilisateur UNIQUE (utilisateur_id),
    CONSTRAINT uq_registration_confirmation_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_registration_confirmation_dates CHECK (
        confirmed_at IS NULL OR confirmed_at <= expires_at
    )
);

CREATE INDEX IF NOT EXISTS idx_registration_confirmation_expiration
    ON gu.registration_confirmation (expires_at)
    WHERE confirmed_at IS NULL;

-- Table: Password-reset requests
-- Only active (therefore confirmed) utilisateurs receive a reset link. The raw link token is
-- never stored; only its SHA-256 hash is persisted. A new request replaces a prior unused token.
CREATE TABLE IF NOT EXISTS gu.password_reset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_password_reset_utilisateur UNIQUE (utilisateur_id),
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_password_reset_dates CHECK (
        used_at IS NULL OR used_at <= expires_at
    )
);

CREATE INDEX IF NOT EXISTS idx_password_reset_expiration
    ON gu.password_reset (expires_at)
    WHERE used_at IS NULL;

-- Table: BASIC_RIGHTS
CREATE TABLE IF NOT EXISTS gu.basic_rights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    br_name VARCHAR(150) NOT NULL,
    CONSTRAINT uq_basic_rights_code UNIQUE (code)
);

-- Table: Associations between user types and basic rights
CREATE TABLE IF NOT EXISTS gu.type_utilisateur_basic_right (
    type_utilisateur_id BIGINT NOT NULL REFERENCES gu.type_utilisateur(id),
    basic_right_id BIGINT NOT NULL REFERENCES gu.basic_rights(id),
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (type_utilisateur_id, basic_right_id)
);

-- An ADMINISTRATEUR type receives every existing basic right.
CREATE OR REPLACE FUNCTION gu.assign_all_basic_rights_to_administrateur()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.code = 'ADMINISTRATEUR' THEN
        INSERT INTO gu.type_utilisateur_basic_right (type_utilisateur_id, basic_right_id)
        SELECT NEW.id, br.id
        FROM gu.basic_rights AS br
        ON CONFLICT DO NOTHING;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_type_utilisateur_assign_administrateur_rights ON gu.type_utilisateur;

CREATE TRIGGER trg_type_utilisateur_assign_administrateur_rights
AFTER INSERT OR UPDATE OF code ON gu.type_utilisateur
FOR EACH ROW
EXECUTE FUNCTION gu.assign_all_basic_rights_to_administrateur();

-- Every newly-created basic right is automatically assigned to ADMINISTRATEUR.
CREATE OR REPLACE FUNCTION gu.assign_basic_right_to_administrateur()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO gu.type_utilisateur_basic_right (type_utilisateur_id, basic_right_id)
    SELECT tu.id, NEW.id
    FROM gu.type_utilisateur AS tu
    WHERE tu.code = 'ADMINISTRATEUR'
    ON CONFLICT DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_basic_right_assign_administrateur ON gu.basic_rights;

CREATE TRIGGER trg_basic_right_assign_administrateur
AFTER INSERT ON gu.basic_rights
FOR EACH ROW
EXECUTE FUNCTION gu.assign_basic_right_to_administrateur();

-- Basic rights cannot be removed or reassigned from the ADMINISTRATEUR type.
CREATE OR REPLACE FUNCTION gu.prevent_administrateur_basic_right_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM gu.type_utilisateur AS tu
        WHERE tu.id = OLD.type_utilisateur_id
          AND tu.code = 'ADMINISTRATEUR'
    ) THEN
        RAISE EXCEPTION 'Basic rights cannot be removed or reassigned from the ADMINISTRATEUR type.';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_type_utilisateur_basic_right_protect_administrateur ON gu.type_utilisateur_basic_right;

CREATE TRIGGER trg_type_utilisateur_basic_right_protect_administrateur
BEFORE DELETE OR UPDATE ON gu.type_utilisateur_basic_right
FOR EACH ROW
EXECUTE FUNCTION gu.prevent_administrateur_basic_right_change();

-- The first basic right: every user type can connect to the application.
INSERT INTO gu.basic_rights (code, br_name)
VALUES ('APP-CONN', 'Connexion a l''application CacaoMARKETCM')
ON CONFLICT (code) DO UPDATE
SET br_name = EXCLUDED.br_name;

INSERT INTO gu.type_utilisateur_basic_right (type_utilisateur_id, basic_right_id)
SELECT tu.id, br.id
FROM gu.type_utilisateur AS tu
CROSS JOIN gu.basic_rights AS br
WHERE br.code = 'APP-CONN'
ON CONFLICT DO NOTHING;

-- Ensure ADMINISTRATEUR is associated with every existing basic right.
INSERT INTO gu.type_utilisateur_basic_right (type_utilisateur_id, basic_right_id)
SELECT tu.id, br.id
FROM gu.type_utilisateur AS tu
CROSS JOIN gu.basic_rights AS br
WHERE tu.code = 'ADMINISTRATEUR'
ON CONFLICT DO NOTHING;

-- Table: Password history
-- Each password row belongs to one utilisateur and preserves the complete password history.
CREATE TABLE IF NOT EXISTS gu.password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id),
    "password" VARCHAR(255) NOT NULL,
    "current" BOOLEAN NOT NULL DEFAULT TRUE,
    date_insertion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_changement TIMESTAMPTZ,
    CONSTRAINT chk_password_history_current_dates CHECK (
        ("current" AND date_changement IS NULL)
        OR (NOT "current" AND date_changement IS NOT NULL)
    )
);

-- A user may have one current password only; prior password rows remain as history.
CREATE UNIQUE INDEX IF NOT EXISTS uq_password_history_current_utilisateur
    ON gu.password_history (utilisateur_id)
    WHERE "current";

CREATE INDEX IF NOT EXISTS idx_password_history_utilisateur_date
    ON gu.password_history (utilisateur_id, date_insertion DESC);

-- Inserting or reactivating a current password archives the prior current password for that user.
-- Password values and their utilisateur association are immutable: insert a new row instead of overwriting history.
CREATE OR REPLACE FUNCTION gu.manage_password_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW."password" IS DISTINCT FROM OLD."password" THEN
            RAISE EXCEPTION 'Password history is immutable. Insert a new password_history row instead.';
        END IF;

        IF NEW.utilisateur_id IS DISTINCT FROM OLD.utilisateur_id THEN
            RAISE EXCEPTION 'A password history row cannot be moved to another utilisateur.';
        END IF;

        IF NOT OLD."current" AND NEW."current" THEN
            UPDATE gu.password_history
            SET "current" = FALSE,
                date_changement = CURRENT_TIMESTAMP
            WHERE "current"
              AND id <> NEW.id
              AND utilisateur_id = NEW.utilisateur_id;

            NEW.date_changement := NULL;
        ELSIF OLD."current" AND NOT NEW."current" THEN
            NEW.date_changement := COALESCE(NEW.date_changement, CURRENT_TIMESTAMP);
        END IF;
    ELSIF TG_OP = 'INSERT' AND NEW."current" THEN
        UPDATE gu.password_history
        SET "current" = FALSE,
            date_changement = CURRENT_TIMESTAMP
        WHERE "current"
          AND utilisateur_id = NEW.utilisateur_id;

        NEW.date_changement := NULL;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_password_history_manage_current ON gu.password_history;

CREATE TRIGGER trg_password_history_manage_current
BEFORE INSERT OR UPDATE OF "password", "current", utilisateur_id ON gu.password_history
FOR EACH ROW
EXECUTE FUNCTION gu.manage_password_history();

-- Development bootstrap administrator. The password value below is a BCrypt hash of `root1234`,
-- never the plaintext password. Change this initial password immediately after the first login.
-- On a re-run, the existing `root` account is promoted to ADMINISTRATEUR but its current password
-- is never replaced; the bootstrap hash is inserted only when no current password exists.
DO $$
DECLARE
    administrator_type_id BIGINT;
    administrator_utilisateur_id BIGINT;
BEGIN
    SELECT id
    INTO STRICT administrator_type_id
    FROM gu.type_utilisateur
    WHERE code = 'ADMINISTRATEUR';

    SELECT id
    INTO administrator_utilisateur_id
    FROM gu.utilisateurs
    WHERE LOWER(login) = 'root'
    FOR UPDATE;

    IF NOT FOUND THEN
        INSERT INTO gu.utilisateurs (
            type_utilisateur_id,
            nom,
            prenom,
            email,
            login,
            statut
        )
        VALUES (
            administrator_type_id,
            'System',
            'Root',
            'root@cacaomarket.local',
            'root',
            'ACTIF'
        )
        RETURNING id INTO administrator_utilisateur_id;
    ELSE
        UPDATE gu.utilisateurs
        SET type_utilisateur_id = administrator_type_id,
            statut = 'ACTIF'
        WHERE id = administrator_utilisateur_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM gu.password_history
        WHERE utilisateur_id = administrator_utilisateur_id
          AND "current" = TRUE
    ) THEN
        INSERT INTO gu.password_history (utilisateur_id, "password", "current")
        VALUES (
            administrator_utilisateur_id,
            '$2a$12$L9cGpgE/8q1pg7YUGiteQ.SuGnfrOOV4rghX1ikMX7ahTju3Gu7HW',
            TRUE
        );
    END IF;
END;
$$;

-- ============================================================================
-- Catalogue cacao, messagerie, négociations et rendez-vous
-- ----------------------------------------------------------------------------
-- These relations carry the buyer/seller features: a VENDEUR publishes cocoa
-- lots, a CLIENT browses the catalogue, opens a conversation per lot, exchanges
-- messages, proposes a negotiation and books a visit. Reference tables keep the
-- filters (region, ville, type de cacao) controlled instead of free text.
-- ============================================================================

-- Table: Regions
CREATE TABLE IF NOT EXISTS gu.region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uq_region_code UNIQUE (code),
    CONSTRAINT uq_region_nom UNIQUE (nom)
);

INSERT INTO gu.region (code, nom)
VALUES
    ('ADAMAOUA', 'Adamaoua'),
    ('CENTRE', 'Centre'),
    ('EST', 'Est'),
    ('EXTREME_NORD', 'Extrême-Nord'),
    ('LITTORAL', 'Littoral'),
    ('NORD', 'Nord'),
    ('NORD_OUEST', 'Nord-Ouest'),
    ('OUEST', 'Ouest'),
    ('SUD', 'Sud'),
    ('SUD_OUEST', 'Sud-Ouest')
ON CONFLICT (code) DO UPDATE
SET nom = EXCLUDED.nom;

-- Table: Villes
-- A city always belongs to one region; it is optional on a lot because a seller
-- may only know the producing area.
CREATE TABLE IF NOT EXISTS gu.ville (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL REFERENCES gu.region(id) ON DELETE CASCADE,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uq_ville_region_nom UNIQUE (region_id, nom)
);

CREATE INDEX IF NOT EXISTS idx_ville_region ON gu.ville (region_id, nom ASC);

INSERT INTO gu.ville (region_id, nom)
SELECT r.id, seed.nom
FROM (
    VALUES
        ('ADAMAOUA', 'Ngaoundéré'), ('ADAMAOUA', 'Meiganga'), ('ADAMAOUA', 'Tibati'),
        ('CENTRE', 'Yaoundé'), ('CENTRE', 'Bafia'), ('CENTRE', 'Mbalmayo'), ('CENTRE', 'Obala'),
        ('EST', 'Bertoua'), ('EST', 'Batouri'), ('EST', 'Yokadouma'),
        ('EXTREME_NORD', 'Maroua'), ('EXTREME_NORD', 'Kousséri'), ('EXTREME_NORD', 'Mokolo'),
        ('LITTORAL', 'Douala'), ('LITTORAL', 'Edéa'), ('LITTORAL', 'Nkongsamba'),
        ('NORD', 'Garoua'), ('NORD', 'Guider'), ('NORD', 'Figuil'),
        ('NORD_OUEST', 'Bamenda'), ('NORD_OUEST', 'Kumbo'), ('NORD_OUEST', 'Wum'),
        ('OUEST', 'Bafoussam'), ('OUEST', 'Bangangté'), ('OUEST', 'Dschang'), ('OUEST', 'Mbouda'),
        ('SUD', 'Ebolowa'), ('SUD', 'Kribi'), ('SUD', 'Sangmélima'),
        ('SUD_OUEST', 'Buéa'), ('SUD_OUEST', 'Kumba'), ('SUD_OUEST', 'Limbé'), ('SUD_OUEST', 'Mamfe')
) AS seed (region_code, nom)
INNER JOIN gu.region r ON r.code = seed.region_code
ON CONFLICT (region_id, nom) DO NOTHING;

-- Table: Types de cacao
-- Controlled vocabulary used by the catalogue filters.
CREATE TABLE IF NOT EXISTS gu.type_cacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    CONSTRAINT uq_type_cacao_code UNIQUE (code),
    CONSTRAINT uq_type_cacao_nom UNIQUE (nom)
);

INSERT INTO gu.type_cacao (code, nom, description)
VALUES
    ('CRIOLLO', 'Criollo', 'Variété fine et aromatique, volumes limités.'),
    ('FORASTERO', 'Forastero', 'Variété courante et robuste, disponible en volume.'),
    ('TRINITARIO', 'Trinitario', 'Hybride entre Criollo et Forastero, bon équilibre arôme/rendement.')
ON CONFLICT (code) DO UPDATE
SET nom = EXCLUDED.nom,
    description = EXCLUDED.description;

-- Table: Lots de cacao
-- One row is one sale announcement published by a VENDEUR. quantite_disponible_kg
-- is reduced by agreed negotiations; the status carries the sale life cycle.
CREATE TABLE IF NOT EXISTS gu.lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendeur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    type_cacao_id BIGINT NOT NULL REFERENCES gu.type_cacao(id),
    titre VARCHAR(150) NOT NULL,
    description TEXT,
    quantite_kg NUMERIC(12,2) NOT NULL,
    quantite_disponible_kg NUMERIC(12,2) NOT NULL,
    prix_kg NUMERIC(12,2) NOT NULL,
    devise VARCHAR(3) NOT NULL DEFAULT 'XAF',
    region_id BIGINT NOT NULL REFERENCES gu.region(id),
    ville_id BIGINT REFERENCES gu.ville(id),
    localisation VARCHAR(200),
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    date_recolte DATE,
    date_disponibilite DATE,
    statut VARCHAR(30) NOT NULL DEFAULT 'BROUILLON',
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_publication TIMESTAMPTZ,
    date_mise_a_jour TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_lots_quantites CHECK (
        quantite_kg > 0
        AND quantite_disponible_kg >= 0
        AND quantite_disponible_kg <= quantite_kg
    ),
    CONSTRAINT chk_lots_prix CHECK (prix_kg > 0),
    CONSTRAINT chk_lots_devise CHECK (char_length(devise) = 3),
    CONSTRAINT chk_lots_statut CHECK (statut IN ('BROUILLON', 'PUBLIE', 'RESERVE', 'VENDU', 'ARCHIVE')),
    CONSTRAINT chk_lots_coordonnees CHECK (
        (latitude IS NULL) = (longitude IS NULL)
        AND (latitude IS NULL OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180))
    ),
    CONSTRAINT chk_lots_publication CHECK (statut = 'BROUILLON' OR date_publication IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_lots_catalogue
    ON gu.lots (statut, region_id, type_cacao_id);
CREATE INDEX IF NOT EXISTS idx_lots_vendeur
    ON gu.lots (vendeur_id, date_creation DESC);
CREATE INDEX IF NOT EXISTS idx_lots_disponibilite
    ON gu.lots (date_disponibilite)
    WHERE statut = 'PUBLIE';

-- Table: Photos d'un lot
CREATE TABLE IF NOT EXISTS gu.lot_medias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL REFERENCES gu.lots(id) ON DELETE CASCADE,
    url VARCHAR(500) NOT NULL,
    legende VARCHAR(200),
    position INTEGER NOT NULL DEFAULT 0,
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lot_medias_lot ON gu.lot_medias (lot_id, position ASC, id ASC);

-- Table: Conversations
-- One thread per lot and per buyer: the buyer asks about an article, then the
-- whole exchange (messages, negotiations, visits) stays in that thread.
CREATE TABLE IF NOT EXISTS gu.conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL REFERENCES gu.lots(id) ON DELETE CASCADE,
    client_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    vendeur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    statut VARCHAR(30) NOT NULL DEFAULT 'OUVERTE',
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dernier_message_at TIMESTAMPTZ,
    CONSTRAINT uq_conversations_lot_client UNIQUE (lot_id, client_id),
    CONSTRAINT chk_conversations_statut CHECK (statut IN ('OUVERTE', 'EN_NEGOCIATION', 'ACCORD', 'CLOTUREE')),
    CONSTRAINT chk_conversations_participants CHECK (client_id <> vendeur_id)
);

CREATE INDEX IF NOT EXISTS idx_conversations_client
    ON gu.conversations (client_id, dernier_message_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_conversations_vendeur
    ON gu.conversations (vendeur_id, dernier_message_at DESC NULLS LAST);

-- Table: Messages
-- Each message belongs to one thread. lu_at records when the other participant
-- read it, which is enough for a two-participant conversation.
CREATE TABLE IF NOT EXISTS gu.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES gu.conversations(id) ON DELETE CASCADE,
    expediteur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    contenu TEXT NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'TEXTE',
    date_envoi TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lu_at TIMESTAMPTZ,
    CONSTRAINT chk_messages_type CHECK (type IN ('TEXTE', 'SYSTEME')),
    CONSTRAINT chk_messages_contenu CHECK (char_length(btrim(contenu)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation
    ON gu.messages (conversation_id, date_envoi ASC, id ASC);

-- Table: Négociations
-- A price/volume proposal inside a conversation. The partial unique index below
-- guarantees at most one open proposal per thread at any time.
CREATE TABLE IF NOT EXISTS gu.negociations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES gu.conversations(id) ON DELETE CASCADE,
    proposeur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    prix_kg NUMERIC(12,2) NOT NULL,
    quantite_kg NUMERIC(12,2) NOT NULL,
    message VARCHAR(500),
    statut VARCHAR(20) NOT NULL DEFAULT 'PROPOSEE',
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_reponse TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    CONSTRAINT chk_negociations_valeurs CHECK (prix_kg > 0 AND quantite_kg > 0),
    CONSTRAINT chk_negociations_statut CHECK (statut IN ('PROPOSEE', 'ACCEPTEE', 'REFUSEE', 'ANNULEE', 'EXPIREE')),
    CONSTRAINT chk_negociations_reponse CHECK (
        (statut = 'PROPOSEE' AND date_reponse IS NULL)
        OR (statut <> 'PROPOSEE' AND date_reponse IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_negociations_proposee_conversation
    ON gu.negociations (conversation_id)
    WHERE statut = 'PROPOSEE';

CREATE INDEX IF NOT EXISTS idx_negociations_conversation
    ON gu.negociations (conversation_id, date_creation DESC);

-- Table: Rendez-vous (visite du site)
-- Proposed in the conversation, accepted by the counterpart. One open visit per
-- thread, same rule as the negotiation proposal.
CREATE TABLE IF NOT EXISTS gu.rendez_vous (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES gu.conversations(id) ON DELETE CASCADE,
    proposeur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id) ON DELETE CASCADE,
    date_proposee TIMESTAMPTZ NOT NULL,
    lieu VARCHAR(200),
    note VARCHAR(500),
    statut VARCHAR(20) NOT NULL DEFAULT 'PROPOSE',
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_reponse TIMESTAMPTZ,
    CONSTRAINT chk_rendez_vous_statut CHECK (statut IN ('PROPOSE', 'ACCEPTE', 'REFUSE', 'ANNULE')),
    CONSTRAINT chk_rendez_vous_reponse CHECK (
        (statut = 'PROPOSE' AND date_reponse IS NULL)
        OR (statut <> 'PROPOSE' AND date_reponse IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rendez_vous_propose_conversation
    ON gu.rendez_vous (conversation_id)
    WHERE statut = 'PROPOSE';

CREATE INDEX IF NOT EXISTS idx_rendez_vous_conversation
    ON gu.rendez_vous (conversation_id, date_proposee ASC);

-- ============================================================================
-- Guards: direct database writes must respect the same rules as the API.
-- ============================================================================

-- A lot belongs to an active VENDEUR account.
CREATE OR REPLACE FUNCTION gu.enforce_lot_vendeur()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    vendeur_code VARCHAR(50);
    vendeur_statut VARCHAR(30);
BEGIN
    SELECT tu.code, u.statut
    INTO vendeur_code, vendeur_statut
    FROM gu.utilisateurs u
    INNER JOIN gu.type_utilisateur tu ON tu.id = u.type_utilisateur_id
    WHERE u.id = NEW.vendeur_id;

    IF vendeur_code IS NULL OR vendeur_code <> 'VENDEUR' OR vendeur_statut <> 'ACTIF' THEN
        RAISE EXCEPTION 'A catalogue lot can only belong to an active VENDEUR account.';
    END IF;

    NEW.date_mise_a_jour := COALESCE(NEW.date_mise_a_jour, CURRENT_TIMESTAMP);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lots_enforce_vendeur ON gu.lots;

CREATE TRIGGER trg_lots_enforce_vendeur
BEFORE INSERT OR UPDATE ON gu.lots
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_lot_vendeur();

-- A conversation is opened by a CLIENT about a lot, with that lot's owner as vendeur.
CREATE OR REPLACE FUNCTION gu.enforce_conversation_participants()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    lot_vendeur_id BIGINT;
    client_code VARCHAR(50);
BEGIN
    SELECT l.vendeur_id INTO lot_vendeur_id
    FROM gu.lots l
    WHERE l.id = NEW.lot_id;

    IF lot_vendeur_id IS NULL THEN
        RAISE EXCEPTION 'The conversation lot does not exist.';
    END IF;

    IF NEW.vendeur_id <> lot_vendeur_id THEN
        RAISE EXCEPTION 'The conversation vendeur must be the lot owner.';
    END IF;

    SELECT tu.code INTO client_code
    FROM gu.utilisateurs u
    INNER JOIN gu.type_utilisateur tu ON tu.id = u.type_utilisateur_id
    WHERE u.id = NEW.client_id;

    IF client_code IS NULL OR client_code <> 'CLIENT' THEN
        RAISE EXCEPTION 'Only a CLIENT account can open a catalogue conversation.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_conversations_enforce_participants ON gu.conversations;

CREATE TRIGGER trg_conversations_enforce_participants
BEFORE INSERT OR UPDATE OF lot_id, client_id, vendeur_id ON gu.conversations
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_conversation_participants();

-- Messages, negotiations and visits can only be posted by a participant of the thread.
CREATE OR REPLACE FUNCTION gu.enforce_conversation_actor()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    actor_id BIGINT;
    is_participant BOOLEAN;
BEGIN
    IF TG_ARGV[0] = 'expediteur_id' THEN
        actor_id := NEW.expediteur_id;
    ELSIF TG_ARGV[0] = 'proposeur_id' THEN
        actor_id := NEW.proposeur_id;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM gu.conversations c
        WHERE c.id = NEW.conversation_id
          AND actor_id IN (c.client_id, c.vendeur_id)
    ) INTO is_participant;

    IF NOT is_participant THEN
        RAISE EXCEPTION 'Only a conversation participant can post in this thread.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_messages_enforce_actor ON gu.messages;
CREATE TRIGGER trg_messages_enforce_actor
BEFORE INSERT OR UPDATE OF conversation_id, expediteur_id ON gu.messages
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_conversation_actor('expediteur_id');

DROP TRIGGER IF EXISTS trg_negociations_enforce_actor ON gu.negociations;
CREATE TRIGGER trg_negociations_enforce_actor
BEFORE INSERT OR UPDATE OF conversation_id, proposeur_id ON gu.negociations
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_conversation_actor('proposeur_id');

DROP TRIGGER IF EXISTS trg_rendez_vous_enforce_actor ON gu.rendez_vous;
CREATE TRIGGER trg_rendez_vous_enforce_actor
BEFORE INSERT OR UPDATE OF conversation_id, proposeur_id ON gu.rendez_vous
FOR EACH ROW
EXECUTE FUNCTION gu.enforce_conversation_actor('proposeur_id');

-- A new message refreshes the thread activity timestamp used by the conversation list.
CREATE OR REPLACE FUNCTION gu.touch_conversation_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE gu.conversations
    SET dernier_message_at = GREATEST(COALESCE(dernier_message_at, NEW.date_envoi), NEW.date_envoi)
    WHERE id = NEW.conversation_id;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_messages_touch_conversation ON gu.messages;

CREATE TRIGGER trg_messages_touch_conversation
AFTER INSERT ON gu.messages
FOR EACH ROW
EXECUTE FUNCTION gu.touch_conversation_activity();

COMMIT;
